import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ProfileDisplay from '../components/ProfileDisplay';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'spotify audio-features with parameters',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="text-center font-bold text-lg">
          spotify audio-features with parameters
        </header>
        <div>
          <ProfileDisplay />
        </div>
        <main>{children}</main>
      </body>
    </html>
  );
}
