'use client';

import { Suspense } from 'react';

//import type { Metadata } from 'next';
//import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

//const inter = Inter({ subsets: ['latin'] });

/*
export const metadata: Metadata = {
  title: 'spotify audio-features with parameters',
  description: 'Generated by create next app',
};
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Suspense? */}
      <Suspense fallback={<div>loading...</div>}>
        <body className=" bg-gray-800">
          <Header />
          <main>{children}</main>
          <Footer />
        </body>
      </Suspense>
    </html>
  );
}

/*
  return (
    <html lang="en">
      <body className="{inter.className} bg-gray-800">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
*/
